version:  '3.0'

services:
  front:
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5002:5002"
    command: yarn run start
